### ISSUE TITLE
Imports aren't working behind proxy / load balancer

### ISSUE THREAD

**Issue by dene14** [FeatureBaseDB/featurebase#1129]
### Expected behavior
Data imported successfully

### Actual behavior
```
2018/02/21 11:54:16 parsing: input.csv
2018/02/21 11:54:16 grouping 22 bits
2018/02/21 11:54:16 importing slice: 0, n=22
Error: import node: host=0.0.0.0:10101, err=Post http://0.0.0.0:10101/import: dial tcp 0.0.0.0:10101: connect: connection refused
```

### Steps to reproduce the behavior
Run import against pilosa endpoint published through a proxy.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
Solo node, official docker image v0.8.8

**Comment by jaffee** [comment]
There are actually two issues at play here - one is that when binding to `0.0.0.0`, Pilosa publishes that to other nodes and via the `/fragment/nodes` endpoint as its address, which is obviously unusable. This is documented at #928 though that may get moved.

The second issue (and this needs to be confirmed) is that even with a proper bind address, imports to a Pilosa cluster behind a proxy will still fail because Pilosa will report its internal addresses in /fragment/nodes and then the client will try to import to those addresses rather than the proxy.

Using Pilosa behind a proxy or load balancer will probably never be optimal from a performance perspective, but I think we can at least make it work. We'll probably need a client option to force a client to always use a proxy address rather than using various addresses from the cluster.

**Comment by dene14** [comment]
More to add...

I think this advertisement scheme is wrong. So for e.g. in docker we have `bind` to 0.0.0.0:10101. From outside this docker container can be accessed

**Comment by dene14** [comment]
Guys, any update on this? Pilosa 1.0 has been released already but the thing still doesn't work

**Comment by jaffee** [comment]
Hi @dene14 - sorry for the delay. It looks like we need to look into the client option which will force it to always use the load balancer address rather than internal Pilosa addresses.

I want to stress though that this is not an ideal environment for Pilosa to operate in - Pilosa and its clients do load balancing amongst themselves, and an external load balancer provides no additional benefit.
