### ISSUE TITLE
Is there the expression like sql "select user_id from ad_log where day between 2018-08-01 and 2018-08-20 group by campaign_id having sum(impression)>10"?

### ISSUE THREAD

**Issue by zhyhang** [FeatureBaseDB/featurebase#1605]
Is there the expression like sql "select user_id from ad_log where day between 2018-08-01 and 2018-08-20 group by campaign_id having sum(impression)>10"?

ad_logs as index
user_id as column
campaign_id as row
time field? or int field? or combination?

**Comment by jaffee** [comment]
@zhyhang do you mean "select COUNT(user_id) from ...", and what are impressions in this case - can you show what the SQL schema and output would look like for this query?

**Comment by zhyhang** [comment]
- I mean select user_id from...
- table ad_log schema:
```sql
...
user_id varchar(32),
campaign_id long,
day int,
impression long,
...
```
- example

user_id | campaign_id | day | impression
------------ | ------------ | ------------ | ------------
1 | 1 | 20180820 | 1
2 | 1 | 20180820 | 1
2 | 1 | 20180820 | 10
3 | 1 | 20180820 | 1
3 | 1 | 20180820 | 10

```sql
select user_id from ad_log where day between 2018-08-01 and 2018-08-20 group by campaign_id having sum(impression)>10
```

**I mean using above sql to get the use_ids: 2,3**

**Comment by jaffee** [comment]
I think you will need to structure your index such that each column is an "impression" and has a field for campaign_id, user_id, timestamp (int field). Then you'd be able to do something like:
```
for x in campaign_ids:
    TopN(user_id, campaign_id=x)
```
You'd have to post-process the results by filtering out when the number of impressions is 10 or less.

There is currently a PR #1496 that is being reviewed which brings some preliminary support for GROUP BY over multiple fields that will make this easier (and more performant). We'll be adding more SQL-like features over the next weeks and months, so something like HAVING will probably not be too far behind.

**Comment by travisturner** [comment]
I tried modeling this two different ways. Neither method works completely because as @jaffee noted, Pilosa does not yet support anything like `HAVING` on the result set. Additionally, Method 1 doesn't work because Pilosa's `GroupBy` currently only supports `COUNT()` and not `SUM()`.

I have described what I did below for informational purposes.

**Method 1**
Model the data as described by the example table above, where Pilosa columns represent `records` (the example table has 5 records).

Create schema:
```
curl http://localhost:10101/index/records -d '{"options": {"keys": false, "trackExistence": false}}'
curl http://localhost:10101/index/records/field/impressions -d '{"options": {"type": "int", "min": 0, "max": 1023}}'
curl http://localhost:10101/index/records/field/user -d '{"options": {"type": "set"}}'
curl http://localhost:10101/index/records/field/campaign -d '{"options": {"type": "set"}}'
curl http://localhost:10101/index/records/field/day -d '{"options": {"type": "int", "min": 20180101, "max": 20201231}}'
```
Define data:
```
[campaign.csv]
1,1
1,2
1,3
1,4
1,5

[day.csv]
1,20180820
2,20180820
3,20180820
4,20180820
5,20180820

[impressions.csv]
1,1
2,1
3,10
4,1
5,10

[user.csv]
1,1
2,2
2,3
3,4
3,5
```
Import data:
```
pilosa import -i records -f impressions impressions.csv
pilosa import -i records -f user user.csv
pilosa import -i records -f day day.csv
pilosa import -i records -f campaign campaign.csv
```
Run query:
```
curl http://localhost:10101/index/records/query -d 'GroupBy(Rows(field=user), Rows(field=campaign), filter=Row(20180801 <= day <= 20180820))'
```
This method is not very useful because of the lack of `SUM()` aggregate support in Pilosa's `GroupBy` query. I will open a follow-up issue suggesting that we consider adding `SUM()` support.

**Method 2**
Model the data by treating every impression as a Pilosa column, so the example table above results in 23 Pilosa columns. 

Create schema:
```
curl http://localhost:10101/index/impressions -d '{"options": {"keys": false, "trackExistence": false}}'
curl http://localhost:10101/index/impressions/field/user -d '{"options": {"type": "set"}}'
curl http://localhost:10101/index/impressions/field/campaign -d '{"options": {"type": "set"}}'
curl http://localhost:10101/index/impressions/field/day -d '{"options": {"type": "int", "min": 20180101, "max": 20201231}}'
```
Define data:
```
[campaign.csv]
1,1
1,2
1,3
1,4
1,5
1,6
1,7
1,8
1,9
1,10
1,11
1,12
1,13
1,14
1,15
1,16
1,17
1,18
1,19
1,20
1,21
1,22
1,23

[day.csv]
1,20180820
2,20180820
3,20180820
4,20180820
5,20180820
6,20180820
7,20180820
8,20180820
9,20180820
10,20180820
11,20180820
12,20180820
13,20180820
14,20180820
15,20180820
16,20180820
17,20180820
18,20180820
19,20180820
20,20180820
21,20180820
22,20180820
23,20180820

[user.csv]
1,1
2,2
2,3
2,4
2,5
2,6
2,7
2,8
2,9
2,10
2,11
2,12
3,13
3,14
3,15
3,16
3,17
3,18
3,19
3,20
3,21
3,22
3,23
```
Import data:
```
pilosa import -i impressions -f user user.csv
pilosa import -i impressions -f day day.csv
pilosa import -i impressions -f campaign campaign.csv
```
Run query:
```
curl http://localhost:10101/index/impressions/query -d 'GroupBy(Rows(field=user), Rows(field=campaign), filter=Row(20180801 <= day <= 20180820))'
```
This method is a little closer to the desired result in that it returns three groupings, two of which have a count of 11. Method 1 is probably the ideal solution because it adheres to the original data model, but there's still a bit of work needed in Pilosa to completely support that method.

**Comment by jaffee** [comment]
#1844 is also related
