### ISSUE TITLE
Allow turning on `trackExistence` for an existing index

### ISSUE THREAD

**Issue by alanbernstein** [FeatureBaseDB/featurebase#1639]
### Description
Regardless of the outcome of the decision to set `trackExistence` to `True` or `False` by default (https://github.com/pilosa/pilosa/issues/1637), a user might expect to be able to switch from `False` to `True` without an unreasonable amount of effort. This is non-trivial because

- It requires scanning all data in the index.
- There's no obvious way to specify that change. This feature is one vote for an API endpoint to modify index options.

For now, it is more reasonable to recreate an index with the required options, especially if `trackExistence=True` is the default. This ticket is to track interest.

### Success criteria (What criteria will consider this ticket closeable?)
An endpoint for modifying index options is available, and enabling `trackExistence` automatically creates the `exists` field appropriately.

**Comment by jaffee** [comment]
I had some thoughts on implementing this. Effectively, I think you would:
1. turn trackExistence on so that new data coming in is tracked.
2. Union every row in every field, then merge that bitmap into the existence bitmap. int fields only need the not-null bitmap of course.

Worst case performance for step 2 is pretty bad, but I think that for most data patterns it can be done rather efficiently. The following will be done on a per-shard basis:
- First perform a TopN on each ranked field, and a count on each int field's not-null bitmap. 
- Starting from the highest count begin unioning rows.
- stop if the bitmap ever becomes completely full

For most uses of Pilosa, the union will quickly become composed of RLE containers with a few long runs - even if there are a few unused columns, continuing to union this with further bitmaps will be very performant. For most shards, in many cases the shard will be completely full after just a few unions. Consider the taxi use case where every column is either a green or yellow cab - most shards will fall completely into one of those categories, and we'll need to do 0 unions to compute the existence bitmap. Any data which has an integer field for every record will just use that field's not-null bitmap.
