### ISSUE TITLE
New field type - ranked set + time

### ISSUE THREAD

**Issue by dmibor** [FeatureBaseDB/featurebase#1648]
### Description
Hi Everyone! 
Wonder if field type that combines functionality of ranked set field and time field could be implemented?
So that it would become possible to do TopN query but filter it based on time windows? E.g. in query language example in addition to “TopN(stargazer, Row(language=1), n=2)” that can tell me top 2 users that have most stars in language 1 from beginning of time - It could give answer to similar question, what are top 2 users that put most start in language 1 during the last month?

This would be really useful for us since our data always has time dimension attached to it and the main goal of the whole system we are designing is to be able to provide answers to historical questions about what happened with this binary matrix over time, compare state 2 months ago to 1 month ago and so on - and right now we are writing POC that would use just time type fields for everything and we would do queries like  `Count(Intersect(Range(<field A row, type=time>, <last month timestamps>), Range(<field B row, type=time>, <last month timestamps>)))` for every single combination of `field A` and `field B` values we have and then stitch results together in application code, i.e. seems like we would kind of simulate functionality very similar to TopN in application code - but probably it would be miles less performant than what TopN could potentially show, wouldn't it?

### Success criteria (What criteria will consider this ticket closeable?)

When we would be able to do TopN for particular time range fast

**Comment by jaffee** [comment]
Hi @dmibor thanks for submitting an issue.

Time fields are implementing by maintaining a separate "view" for every quantum of time that exists. So if the field is configured to "YM", then it would contain views for 2016, 2017... 2016-01, 2016-02... etc. In addition to these views, a "standard" view is also maintained which contains any bit which has been set regardless of the associated timestamp. 

Based on some internal discussion, it should be fairly straightforward to enable a ranked cache on the standard view which would then support `TopN` queries with no change to the query language. Because TopN queries can take an arbitrary bitmap as a filter, it would be possible to do something like `TopN(sometimefield, Range(sometimefield=5, 2016-02-05, 2016-04-05))` This would give you the top rows in `sometimefield` sorted by number of bits set in columns where row 5 has a set bit between February 5th and April 5th in 2016.

If you wanted to do TopN for a specific time range without a filter, you'd either have to (a) create a filter which is a union of all rows in `sometimefield` during that time range, or (b) maintain a separate row which gets set whenever any row gets a set bit in `sometimefield` - this would basically mean always having the Union from option (a) precomputed.

So in your example, with the proposed change, it would be possible to `TopN(stargazer, Range(language=1, 2016-02-01, 2016-04-01), n=2)` assuming that stargazer and language are time fields. Keep in mind that the counts returned are the number of columns that have a set bit anywhere in that time range for that row. If a bit is set in the same row/col multiple times within the time range that will not be reflected in the count.

Does that sound like it would be helpful?

**Comment by jaffee** [comment]
What I meant by (b) was that you would set an additional bit for every bit set in the time field. E.G. if you are doing `Set(timefield=2, 2016-04-05)` you would also do `Set(trackfield=0, 2016-04-05)`. So regardless of what row is being set in timefield, you set `trackfield=0` with the same timestamp. A `Range` query on `trackfield=0` then returns exactly the same as `Union`ing all rows of `timefield` in the same time range.

Interestingly, if we made the `existence` field a time field I think that could the same purpose, though that would add a significant amount of overhead.

**Comment by travisturner** [comment]
Got it. That makes more sense regarding (b). So the suggestion is to maintain an existence row in each time-quantum view of a time field. (I don't think it would be wise to use the index's `existence` field because that wouldn't be field specific and multiple `time` fields in the same index would cause problems).

**Comment by dmibor** [comment]
Hey, @jaffee, @travisturner ! Thank you for your replies, this discussion is definitely giving us way to move forward!

> Does that sound like it would be helpful?

Idea definitely is! Reading your reply it occurred to me that I can achieve the same thing as enabling ranked cache to standard view even now by using ranked set and time field together in sync (setting bit in both fields at the same time same way as you propose in (b) - when doing `Set(timefield=2, 2016-04-05)` I would also do `Set(rankedfield=2)` ). Which would give the the opportunity to do the same query like that - `TopN(rankedfield, Range(timefield=5, 2016-02-05, 2016-04-05))`. So enabling ranked cache on standard view would not give additional functionality as it seems to me, looks more like a hack that can help save space of one standard view, not sure it's worth adding additional complexity...

> If you wanted to do TopN for a specific time range without a filter, you'd either have to (a) create a filter which is a union of all rows in `sometimefield` during that time range, or (b) maintain a separate row which gets set whenever any row gets a set bit in `sometimefield` - this would basically mean always having the Union from option (a) precomputed.

Yeah that is exactly what I wanted, thank you for this idea @jaffee ! It's not too useful to intersect with specific row in this query `TopN(sometimefield, Range(sometimefield=5, 2016-02-05, 2016-04-05))` but (b) will definitely do the trick

On the other hand this approach has quite important limitations in case if my cacheSize is significantly less than number of rows in the ranked field - in that case I can not trust this query to catch and return bursts, anomalies, since they most likely would not be present in ranked cache. E.g. in stargazer example if user behavior is such that it never present in ranked cache - is generally on average not active and stars almost no repos - but suddenly in particular time window starts to be very active, I might or might not see this depending on how active he is and on how big of a time window im looking at. And it so happens that this info might be extremely valuable, at least in our case.

Initially I was thinking about something like @travisturner mentioned `TopN(sometimefield, 2016-02-05, 2016-04-05, n=5))` but I imagine that would require to have ranked cache for each view of time field that would solve above limitation but probably take a lot of space and add additional complexity  and need to merge results from multiple caches?

**Comment by dmibor** [comment]
> Based on some internal discussion, it should be fairly straightforward to enable a ranked cache on the standard view which would then support `TopN` queries with no change to the query language. Because TopN queries can take an arbitrary bitmap as a filter, it would be possible to do something like `TopN(sometimefield, Range(sometimefield=5, 2016-02-05, 2016-04-05))` This would give you the top rows in `sometimefield` sorted by number of bits set in columns where row 5 has a set bit between February 5th and April 5th in 2016.

Btw, wanted to clarify if I'am correct to say that it would give me top rows in `sometimefield` sorted by number of bits set **in standard view** but with counts equal to number of bits set in row 5 between February 5th and April 5th in 2016? I.e. sort order will be according to standard view , not according to row=5?

**Comment by jaffee** [comment]
Adding the ability to have a ranked cache on the standard view of a time field should be a pretty easy change, so I think that at least is worth the complexity. The follow-on question is whether we want to explicitly support TopN over a time range without having to pass a filter query - more on this below.

A cache size of ~200k is totally feasible, though it might slow down queries which are forced to traverse the long tail of the cache - this is something you'll have to experiment with on your workload and see if it's ok.

Adding a ranked cache on each view of the time field is an interesting idea - I'd have to think about the consequences of that a bit more. Many smaller caches would probably be more performant than one large one, and merging the results together doesn't seem like it would be too expensive - we already have code that does essentially this for merging the results of TopN from different shards. IMO it's mostly a question of added complexity both on the API side and in the code. I'll be interested to hear others' thoughts on this.

Summary:
1. definitely add the ability to have a ranked cache on the standard view of a time field.
2. consider supporting the passing of a time range to TopN directly - I see two options for doing this:
   (a) maintain or calculate a single-row time range field which is the union of all rows in the target field and pass it as a filter to the TopN query.
   (b) add a ranked cache to every view of the time field - execute the TopN on the views which are in the time range and merge the results.

I need to think more about 2a vs 2b to convince myself that they are fundamentally equivalent and quantify the tradeoffs a bit.

**Comment by travisturner** [comment]
I think if you assume that each `row`/`column` combination has only **one** timestamp associated with it, then 2a and 2b are equivalent as long as the cache sizes of the standard view (for 2a) and the time views (for 2b) can accommodate enough of the row set to support the query.

2b is a bit more complex due to the re-queries it has to do (similar to the way we currently re-query shards for TopN), but I think—depending on the `timeQuantum` for the field—it might allow for smaller caches.

With that said, it's not obvious to me which would be more performant. I think it would depend on the data and query patterns.

**Comment by jaffee** [comment]
@dmibor I think you're right, although your notation is unclear to me.

The result of the TopN query you posted would be a list of each row id in `sometimefield` along with a count which is the intersection of all the columns set in that row (regardless of time) with all the columns set in *any* row within the time range. So if, for example, row 7 had every column set during the time range, then the query would act like a normal TopN query which is not what we're looking for.

Having a ranked cache on the standard view still might be useful, but not for doing TopN queries on a time range - for that I think we will need to add a ranked cache on every view.

**Comment by dmibor** [comment]
> @dmibor I think you're right, although your notation is unclear to me.

Sorry about that, diverged from Pilosa notations. Was not too successful attempt to shorten and be more visually clear:
```
a*b => Intersect(a,b)
a+b => Union(a,b)
```
And also did this transformation:
```
Intersect(a,Union(b,c)) = Union( Intersect(a,b), Intersect(a,c) )
```
