### ISSUE TITLE
Open File Limit: invalid argument

### ISSUE THREAD

**Issue by CLoZengineer** [FeatureBaseDB/featurebase#2163]
From Discord: https://discord.com/channels/997235309131595786/1017121543861583873/1017838531470688356

```
Going through the docs to see if I can figure it out. I previously got Pilosa running locally on my Mac..here's the current state:

sidekick:featurebase-v3.20.0-darwin-amd64 kord$ ./featurebase server -c featurebase.conf
running server: setting resource limits: setting open file limit: invalid argument
[12:47 PM]
Happy to post the config, which I copy/pasted from the guide.
[12:48 PM]
Running as root has no effect on output.
```

**Comment by CLoZengineer** [comment]
Also want to ensure the documentation for this config is easy to find.

**Comment by kordless** [comment]
Using the stock config:

`
name = "featurebase"
bind = "0.0.0.0:10101"
bind-grpc = "0.0.0.0:20101"
max-query-memory = 200000000
max-file-count = 2000

data-dir = "/var/lib/molecula"
log-path = "/var/log/molecula/featurebase.log"

[cluster]
    name = "cluster"
    replicas = 1

[etcd]
    listen-client-address = "http://localhost:10401"
    listen-peer-address = "http://localhost:10301"
    initial-cluster = "featurebase=http://localhost:10301"
`

**Comment by fhaynes** [comment]
The problem is the default ulimit on macOS mojave seems to 10240. @kordless was able to get it working by setting the max no of open files to that. There should be a way to increase the max no of open files, but `sudo ulimit -n 100000` is returning:
```
sh-3.2# sudo ulimit -n 1000000
/usr/bin/ulimit: line 4: ulimit: open files: cannot modify limit: Invalid argument
```

This may be a limit specific to mojave, or it may need to be done from launchctl. @CLoZengineer it's probably worth updating the docs to note that we only test/support the most recent version of macOS. This will probably be an issue for anyone trying to run featurebase on mojave or older.

@kordless did figure out that they could update it via kern.maxf:
```
sh-3.2# sysctl -a |grep kern.maxf
kern.maxfiles: 12288
kern.maxfilesperproc: 10240
```

**Comment by kordless** [comment]
I got this working by adding 

`max-file-count=10240`

to the config file, stored in /etc/featurebase.conf. 

I then ran `sudo ulimit -n 10240` and started the server with `sudo featurebase server -c /etc/featurebase.conf`.

Running a ulimit higher than 12288 resulted in a similar error as received from running featurebase, so the origin of the error was coming from the kernel, not featurebase.

**Comment by kordless** [comment]
Some version info for OSX:

macOS Mojave
Version 10.14.6 (18G9323)
Memory 8GB
