### ISSUE TITLE
About release version scheme

### ISSUE THREAD

**Issue by chenrui333** [FeatureBaseDB/featurebase#2194]
I know `featurebase` is derived from `pilosa`, but the latest release for `pilosa` was 1.4.1, and it looks like the new community version for `featurebase` is with `v1.0.0-community`? Just curious, why not just use `v2.0.0` instead?

Asking because I am thinking to [revive](https://github.com/Homebrew/homebrew-core/pull/95805) [the homebrew formula](https://formulae.brew.sh/formula/pilosa), but the version scheme really bothers me. Thanks!

**Comment by kordless** [comment]
I am in agreement with you regarding the version number and do wish we had put more thought into it before the re-release a few months ago.

I was thinking about this while doing the last release, so I'm grateful you opened this issue for discussion.

Within a release or two, SQL3 should be fully integrated into the UI and likely made the default query method. Technically, a major version bump at that time would make sense due to the API becoming incompatible with previous releases. As it stands right now, these versions still support the older calling methods...

**Comment by chenrui333** [comment]
> I am in agreement with you regarding the version number and do wish we had put more thought into it before the re-release a few months ago.
> 
> I was thinking about this while doing the last release, so I'm grateful you opened this issue for discussion.
No worries, trying to help here. :)

> 
> Within a release or two, SQL3 should be fully integrated into the UI and likely made the default query method. Technically, a major version bump at that time would make sense due to the API becoming incompatible with previous releases. As it stands right now, these versions still support the older calling methods...

The project renaming should already granted the major release (the artifact got name change?), and regarding the API version stuff, I think either it would be managed separately (I see somebody are doing that), or, we can just do another major version bump regarding the incompatibility part.

Let me know if that makes sense.

**Comment by kordless** [comment]
Closing this as the versions are now updated! @chenrui333 be sure to join our Discord if you need anything!
