### ISSUE TITLE
Support renaming indexes

### ISSUE THREAD

**Issue by alanbernstein** [FeatureBaseDB/featurebase#411]
### Description
SQL has the `ALTER` command, Pilosa has no analogous command.

### Success criteria (What criteria will consider this ticket closeable?)
The ability to rename databases.

**Comment by travisturner** [comment]
This is really dependent upon using internal names for indexes. We don't want to change the name of an index directly, because that would require moving fragments around (based on the hash algorithm). But if we kept an internal index name, and the external index name was just an alias, then that could easily be changed.
