### ISSUE TITLE
Feature Suggestion: Support Badger (as well as Boltdb)

### ISSUE THREAD

**Issue by joeblew99** [FeatureBaseDB/featurebase#862]
Badger is a replacement for BoltDB. 

https://github.com/dgraph-io/badger/tree/develop

https://blog.dgraph.io/post/badger/

I would like to suggest we look at supporting it because it has about 10 times higher Perf than BoltDB in write mode. Reads are still blazing fast.

My testing on Servers and Mobiles shows not issues. 
MVCC Transaction support landed in the develop branch a few days ago and is being dog fooded now.

**Comment by jaffee** [comment]
Hi @joeblew99 - thanks for bringing this to our attention. We've actually had our eye on badger since it was initially released, but usage of the attributes feature in Pilosa (at least for us), has been pretty sparse, and so it hasn't been a high-priority target for refinement and optimization.

We'd love to hear more about how you're using attributes either in this issue, or via email/phone if you'd rather not share details publicly. Feel free to drop us a line at dev@pilosa.com

**Comment by joeblew99** [comment]
refer you to the experiences with bleve 

https://github.com/blevesearch/bleve/issues/591#issuecomment-333499291

**Comment by travisturner** [comment]
Now that the attribute store is behind an interface, it should be fairly easy to add a badger implementation. We don't have this in the short-term pipeline but would be happy to review any PR or help with the implementation.
